-- AlterTable
ALTER TABLE "Business" ADD COLUMN "staff" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "services" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "customers" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "checkouts" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "promotions" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN "bookingSettings" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN "botSettings" JSONB NOT NULL DEFAULT '{}';
